//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 17.0.33122.133
// 
namespace ToDoApp.BikeWebService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private int AppIdField;
        
        private string LoginField;
        
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int AppId {
            get {
                return this.AppIdField;
            }
            set {
                if ((this.AppIdField.Equals(value) != true)) {
                    this.AppIdField = value;
                    this.RaisePropertyChanged("AppId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseModelOfUser", Namespace="http://tempuri.org/")]
    public partial class ResponseModelOfUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ToDoApp.BikeWebService.User DataField;
        
        private int resultCodeField;
        
        private string messageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ToDoApp.BikeWebService.User Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                if ((this.resultCodeField.Equals(value) != true)) {
                    this.resultCodeField = value;
                    this.RaisePropertyChanged("resultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseModelOfListOfUser", Namespace="http://tempuri.org/")]
    public partial class ResponseModelOfListOfUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<ToDoApp.BikeWebService.User> DataField;
        
        private int resultCodeField;
        
        private string messageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<ToDoApp.BikeWebService.User> Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                if ((this.resultCodeField.Equals(value) != true)) {
                    this.resultCodeField = value;
                    this.RaisePropertyChanged("resultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseModelOfOrder", Namespace="http://tempuri.org/")]
    public partial class ResponseModelOfOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ToDoApp.BikeWebService.Order DataField;
        
        private int resultCodeField;
        
        private string messageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ToDoApp.BikeWebService.Order Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                if ((this.resultCodeField.Equals(value) != true)) {
                    this.resultCodeField = value;
                    this.RaisePropertyChanged("resultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://tempuri.org/")]
    public partial class Order : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int TaskIdField;
        
        private int AppIdField;
        
        private string HeaderField;
        
        private string DescriptionField;
        
        private int StateField;
        
        private string TaskIdKeyField;
        
        private System.DateTime InitDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TaskId {
            get {
                return this.TaskIdField;
            }
            set {
                if ((this.TaskIdField.Equals(value) != true)) {
                    this.TaskIdField = value;
                    this.RaisePropertyChanged("TaskId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int AppId {
            get {
                return this.AppIdField;
            }
            set {
                if ((this.AppIdField.Equals(value) != true)) {
                    this.AppIdField = value;
                    this.RaisePropertyChanged("AppId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TaskIdKey {
            get {
                return this.TaskIdKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskIdKeyField, value) != true)) {
                    this.TaskIdKeyField = value;
                    this.RaisePropertyChanged("TaskIdKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime InitDate {
            get {
                return this.InitDateField;
            }
            set {
                if ((this.InitDateField.Equals(value) != true)) {
                    this.InitDateField = value;
                    this.RaisePropertyChanged("InitDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseModelOfListOfOrder", Namespace="http://tempuri.org/")]
    public partial class ResponseModelOfListOfOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<ToDoApp.BikeWebService.Order> DataField;
        
        private int resultCodeField;
        
        private string messageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<ToDoApp.BikeWebService.Order> Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                if ((this.resultCodeField.Equals(value) != true)) {
                    this.resultCodeField = value;
                    this.RaisePropertyChanged("resultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseModelOfInt32", Namespace="http://tempuri.org/")]
    public partial class ResponseModelOfInt32 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int DataField;
        
        private int resultCodeField;
        
        private string messageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                if ((this.resultCodeField.Equals(value) != true)) {
                    this.resultCodeField = value;
                    this.RaisePropertyChanged("resultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BikeWebService.BikeWebServiceSoap")]
    public interface BikeWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogIn", ReplyAction="*")]
        System.Threading.Tasks.Task<ToDoApp.BikeWebService.LogInResponse> LogInAsync(ToDoApp.BikeWebService.LogInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogInAsAdministrator", ReplyAction="*")]
        System.Threading.Tasks.Task<ToDoApp.BikeWebService.LogInAsAdministratorResponse> LogInAsAdministratorAsync(ToDoApp.BikeWebService.LogInAsAdministratorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        System.Threading.Tasks.Task<ToDoApp.BikeWebService.RegisterResponse> RegisterAsync(ToDoApp.BikeWebService.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ToDoApp.BikeWebService.EditUserResponse> EditUserAsync(ToDoApp.BikeWebService.EditUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<ToDoApp.BikeWebService.GetUsersResponse> GetUsersAsync(ToDoApp.BikeWebService.GetUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTask", ReplyAction="*")]
        System.Threading.Tasks.Task<ToDoApp.BikeWebService.GetTaskResponse> GetTaskAsync(ToDoApp.BikeWebService.GetTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTasks", ReplyAction="*")]
        System.Threading.Tasks.Task<ToDoApp.BikeWebService.GetTasksResponse> GetTasksAsync(ToDoApp.BikeWebService.GetTasksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<ToDoApp.BikeWebService.AddOrderResponse> AddOrderAsync(ToDoApp.BikeWebService.AddOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<ToDoApp.BikeWebService.EditOrderResponse> EditOrderAsync(ToDoApp.BikeWebService.EditOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<ToDoApp.BikeWebService.DeleteOrderResponse> DeleteOrderAsync(ToDoApp.BikeWebService.DeleteOrderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogIn", Namespace="http://tempuri.org/", Order=0)]
        public ToDoApp.BikeWebService.LogInRequestBody Body;
        
        public LogInRequest() {
        }
        
        public LogInRequest(ToDoApp.BikeWebService.LogInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ToDoApp.BikeWebService.User user;
        
        public LogInRequestBody() {
        }
        
        public LogInRequestBody(ToDoApp.BikeWebService.User user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogInResponse", Namespace="http://tempuri.org/", Order=0)]
        public ToDoApp.BikeWebService.LogInResponseBody Body;
        
        public LogInResponse() {
        }
        
        public LogInResponse(ToDoApp.BikeWebService.LogInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ToDoApp.BikeWebService.ResponseModelOfUser LogInResult;
        
        public LogInResponseBody() {
        }
        
        public LogInResponseBody(ToDoApp.BikeWebService.ResponseModelOfUser LogInResult) {
            this.LogInResult = LogInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInAsAdministratorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogInAsAdministrator", Namespace="http://tempuri.org/", Order=0)]
        public ToDoApp.BikeWebService.LogInAsAdministratorRequestBody Body;
        
        public LogInAsAdministratorRequest() {
        }
        
        public LogInAsAdministratorRequest(ToDoApp.BikeWebService.LogInAsAdministratorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInAsAdministratorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ToDoApp.BikeWebService.User user;
        
        public LogInAsAdministratorRequestBody() {
        }
        
        public LogInAsAdministratorRequestBody(ToDoApp.BikeWebService.User user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInAsAdministratorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogInAsAdministratorResponse", Namespace="http://tempuri.org/", Order=0)]
        public ToDoApp.BikeWebService.LogInAsAdministratorResponseBody Body;
        
        public LogInAsAdministratorResponse() {
        }
        
        public LogInAsAdministratorResponse(ToDoApp.BikeWebService.LogInAsAdministratorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInAsAdministratorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ToDoApp.BikeWebService.ResponseModelOfUser LogInAsAdministratorResult;
        
        public LogInAsAdministratorResponseBody() {
        }
        
        public LogInAsAdministratorResponseBody(ToDoApp.BikeWebService.ResponseModelOfUser LogInAsAdministratorResult) {
            this.LogInAsAdministratorResult = LogInAsAdministratorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://tempuri.org/", Order=0)]
        public ToDoApp.BikeWebService.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(ToDoApp.BikeWebService.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ToDoApp.BikeWebService.User user;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(ToDoApp.BikeWebService.User user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public ToDoApp.BikeWebService.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(ToDoApp.BikeWebService.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ToDoApp.BikeWebService.ResponseModelOfUser RegisterResult;
        
        public RegisterResponseBody() {
        }
        
        public RegisterResponseBody(ToDoApp.BikeWebService.ResponseModelOfUser RegisterResult) {
            this.RegisterResult = RegisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditUser", Namespace="http://tempuri.org/", Order=0)]
        public ToDoApp.BikeWebService.EditUserRequestBody Body;
        
        public EditUserRequest() {
        }
        
        public EditUserRequest(ToDoApp.BikeWebService.EditUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ToDoApp.BikeWebService.User user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ToDoApp.BikeWebService.User newUser;
        
        public EditUserRequestBody() {
        }
        
        public EditUserRequestBody(ToDoApp.BikeWebService.User user, ToDoApp.BikeWebService.User newUser) {
            this.user = user;
            this.newUser = newUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public ToDoApp.BikeWebService.EditUserResponseBody Body;
        
        public EditUserResponse() {
        }
        
        public EditUserResponse(ToDoApp.BikeWebService.EditUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ToDoApp.BikeWebService.ResponseModelOfUser EditUserResult;
        
        public EditUserResponseBody() {
        }
        
        public EditUserResponseBody(ToDoApp.BikeWebService.ResponseModelOfUser EditUserResult) {
            this.EditUserResult = EditUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsers", Namespace="http://tempuri.org/", Order=0)]
        public ToDoApp.BikeWebService.GetUsersRequestBody Body;
        
        public GetUsersRequest() {
        }
        
        public GetUsersRequest(ToDoApp.BikeWebService.GetUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ToDoApp.BikeWebService.User user;
        
        public GetUsersRequestBody() {
        }
        
        public GetUsersRequestBody(ToDoApp.BikeWebService.User user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public ToDoApp.BikeWebService.GetUsersResponseBody Body;
        
        public GetUsersResponse() {
        }
        
        public GetUsersResponse(ToDoApp.BikeWebService.GetUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ToDoApp.BikeWebService.ResponseModelOfListOfUser GetUsersResult;
        
        public GetUsersResponseBody() {
        }
        
        public GetUsersResponseBody(ToDoApp.BikeWebService.ResponseModelOfListOfUser GetUsersResult) {
            this.GetUsersResult = GetUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTask", Namespace="http://tempuri.org/", Order=0)]
        public ToDoApp.BikeWebService.GetTaskRequestBody Body;
        
        public GetTaskRequest() {
        }
        
        public GetTaskRequest(ToDoApp.BikeWebService.GetTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string taskIDKey;
        
        public GetTaskRequestBody() {
        }
        
        public GetTaskRequestBody(string taskIDKey) {
            this.taskIDKey = taskIDKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTaskResponse", Namespace="http://tempuri.org/", Order=0)]
        public ToDoApp.BikeWebService.GetTaskResponseBody Body;
        
        public GetTaskResponse() {
        }
        
        public GetTaskResponse(ToDoApp.BikeWebService.GetTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ToDoApp.BikeWebService.ResponseModelOfOrder GetTaskResult;
        
        public GetTaskResponseBody() {
        }
        
        public GetTaskResponseBody(ToDoApp.BikeWebService.ResponseModelOfOrder GetTaskResult) {
            this.GetTaskResult = GetTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTasksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTasks", Namespace="http://tempuri.org/", Order=0)]
        public ToDoApp.BikeWebService.GetTasksRequestBody Body;
        
        public GetTasksRequest() {
        }
        
        public GetTasksRequest(ToDoApp.BikeWebService.GetTasksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTasksRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ToDoApp.BikeWebService.User user;
        
        public GetTasksRequestBody() {
        }
        
        public GetTasksRequestBody(ToDoApp.BikeWebService.User user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTasksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTasksResponse", Namespace="http://tempuri.org/", Order=0)]
        public ToDoApp.BikeWebService.GetTasksResponseBody Body;
        
        public GetTasksResponse() {
        }
        
        public GetTasksResponse(ToDoApp.BikeWebService.GetTasksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTasksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ToDoApp.BikeWebService.ResponseModelOfListOfOrder GetTasksResult;
        
        public GetTasksResponseBody() {
        }
        
        public GetTasksResponseBody(ToDoApp.BikeWebService.ResponseModelOfListOfOrder GetTasksResult) {
            this.GetTasksResult = GetTasksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOrder", Namespace="http://tempuri.org/", Order=0)]
        public ToDoApp.BikeWebService.AddOrderRequestBody Body;
        
        public AddOrderRequest() {
        }
        
        public AddOrderRequest(ToDoApp.BikeWebService.AddOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ToDoApp.BikeWebService.User user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ToDoApp.BikeWebService.Order order;
        
        public AddOrderRequestBody() {
        }
        
        public AddOrderRequestBody(ToDoApp.BikeWebService.User user, ToDoApp.BikeWebService.Order order) {
            this.user = user;
            this.order = order;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public ToDoApp.BikeWebService.AddOrderResponseBody Body;
        
        public AddOrderResponse() {
        }
        
        public AddOrderResponse(ToDoApp.BikeWebService.AddOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ToDoApp.BikeWebService.ResponseModelOfOrder AddOrderResult;
        
        public AddOrderResponseBody() {
        }
        
        public AddOrderResponseBody(ToDoApp.BikeWebService.ResponseModelOfOrder AddOrderResult) {
            this.AddOrderResult = AddOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditOrder", Namespace="http://tempuri.org/", Order=0)]
        public ToDoApp.BikeWebService.EditOrderRequestBody Body;
        
        public EditOrderRequest() {
        }
        
        public EditOrderRequest(ToDoApp.BikeWebService.EditOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ToDoApp.BikeWebService.User user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ToDoApp.BikeWebService.Order order;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ToDoApp.BikeWebService.Order orderOld;
        
        public EditOrderRequestBody() {
        }
        
        public EditOrderRequestBody(ToDoApp.BikeWebService.User user, ToDoApp.BikeWebService.Order order, ToDoApp.BikeWebService.Order orderOld) {
            this.user = user;
            this.order = order;
            this.orderOld = orderOld;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public ToDoApp.BikeWebService.EditOrderResponseBody Body;
        
        public EditOrderResponse() {
        }
        
        public EditOrderResponse(ToDoApp.BikeWebService.EditOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ToDoApp.BikeWebService.ResponseModelOfOrder EditOrderResult;
        
        public EditOrderResponseBody() {
        }
        
        public EditOrderResponseBody(ToDoApp.BikeWebService.ResponseModelOfOrder EditOrderResult) {
            this.EditOrderResult = EditOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteOrder", Namespace="http://tempuri.org/", Order=0)]
        public ToDoApp.BikeWebService.DeleteOrderRequestBody Body;
        
        public DeleteOrderRequest() {
        }
        
        public DeleteOrderRequest(ToDoApp.BikeWebService.DeleteOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ToDoApp.BikeWebService.User user;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int orderId;
        
        public DeleteOrderRequestBody() {
        }
        
        public DeleteOrderRequestBody(ToDoApp.BikeWebService.User user, int orderId) {
            this.user = user;
            this.orderId = orderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public ToDoApp.BikeWebService.DeleteOrderResponseBody Body;
        
        public DeleteOrderResponse() {
        }
        
        public DeleteOrderResponse(ToDoApp.BikeWebService.DeleteOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ToDoApp.BikeWebService.ResponseModelOfInt32 DeleteOrderResult;
        
        public DeleteOrderResponseBody() {
        }
        
        public DeleteOrderResponseBody(ToDoApp.BikeWebService.ResponseModelOfInt32 DeleteOrderResult) {
            this.DeleteOrderResult = DeleteOrderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BikeWebServiceSoapChannel : ToDoApp.BikeWebService.BikeWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BikeWebServiceSoapClient : System.ServiceModel.ClientBase<ToDoApp.BikeWebService.BikeWebServiceSoap>, ToDoApp.BikeWebService.BikeWebServiceSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BikeWebServiceSoapClient() : 
                base(BikeWebServiceSoapClient.GetDefaultBinding(), BikeWebServiceSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BikeWebServiceSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BikeWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(BikeWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), BikeWebServiceSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BikeWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BikeWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BikeWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BikeWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BikeWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ToDoApp.BikeWebService.LogInResponse> ToDoApp.BikeWebService.BikeWebServiceSoap.LogInAsync(ToDoApp.BikeWebService.LogInRequest request) {
            return base.Channel.LogInAsync(request);
        }
        
        public System.Threading.Tasks.Task<ToDoApp.BikeWebService.LogInResponse> LogInAsync(ToDoApp.BikeWebService.User user) {
            ToDoApp.BikeWebService.LogInRequest inValue = new ToDoApp.BikeWebService.LogInRequest();
            inValue.Body = new ToDoApp.BikeWebService.LogInRequestBody();
            inValue.Body.user = user;
            return ((ToDoApp.BikeWebService.BikeWebServiceSoap)(this)).LogInAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ToDoApp.BikeWebService.LogInAsAdministratorResponse> ToDoApp.BikeWebService.BikeWebServiceSoap.LogInAsAdministratorAsync(ToDoApp.BikeWebService.LogInAsAdministratorRequest request) {
            return base.Channel.LogInAsAdministratorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ToDoApp.BikeWebService.LogInAsAdministratorResponse> LogInAsAdministratorAsync(ToDoApp.BikeWebService.User user) {
            ToDoApp.BikeWebService.LogInAsAdministratorRequest inValue = new ToDoApp.BikeWebService.LogInAsAdministratorRequest();
            inValue.Body = new ToDoApp.BikeWebService.LogInAsAdministratorRequestBody();
            inValue.Body.user = user;
            return ((ToDoApp.BikeWebService.BikeWebServiceSoap)(this)).LogInAsAdministratorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ToDoApp.BikeWebService.RegisterResponse> ToDoApp.BikeWebService.BikeWebServiceSoap.RegisterAsync(ToDoApp.BikeWebService.RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<ToDoApp.BikeWebService.RegisterResponse> RegisterAsync(ToDoApp.BikeWebService.User user) {
            ToDoApp.BikeWebService.RegisterRequest inValue = new ToDoApp.BikeWebService.RegisterRequest();
            inValue.Body = new ToDoApp.BikeWebService.RegisterRequestBody();
            inValue.Body.user = user;
            return ((ToDoApp.BikeWebService.BikeWebServiceSoap)(this)).RegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ToDoApp.BikeWebService.EditUserResponse> ToDoApp.BikeWebService.BikeWebServiceSoap.EditUserAsync(ToDoApp.BikeWebService.EditUserRequest request) {
            return base.Channel.EditUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ToDoApp.BikeWebService.EditUserResponse> EditUserAsync(ToDoApp.BikeWebService.User user, ToDoApp.BikeWebService.User newUser) {
            ToDoApp.BikeWebService.EditUserRequest inValue = new ToDoApp.BikeWebService.EditUserRequest();
            inValue.Body = new ToDoApp.BikeWebService.EditUserRequestBody();
            inValue.Body.user = user;
            inValue.Body.newUser = newUser;
            return ((ToDoApp.BikeWebService.BikeWebServiceSoap)(this)).EditUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ToDoApp.BikeWebService.GetUsersResponse> ToDoApp.BikeWebService.BikeWebServiceSoap.GetUsersAsync(ToDoApp.BikeWebService.GetUsersRequest request) {
            return base.Channel.GetUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ToDoApp.BikeWebService.GetUsersResponse> GetUsersAsync(ToDoApp.BikeWebService.User user) {
            ToDoApp.BikeWebService.GetUsersRequest inValue = new ToDoApp.BikeWebService.GetUsersRequest();
            inValue.Body = new ToDoApp.BikeWebService.GetUsersRequestBody();
            inValue.Body.user = user;
            return ((ToDoApp.BikeWebService.BikeWebServiceSoap)(this)).GetUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ToDoApp.BikeWebService.GetTaskResponse> ToDoApp.BikeWebService.BikeWebServiceSoap.GetTaskAsync(ToDoApp.BikeWebService.GetTaskRequest request) {
            return base.Channel.GetTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<ToDoApp.BikeWebService.GetTaskResponse> GetTaskAsync(string taskIDKey) {
            ToDoApp.BikeWebService.GetTaskRequest inValue = new ToDoApp.BikeWebService.GetTaskRequest();
            inValue.Body = new ToDoApp.BikeWebService.GetTaskRequestBody();
            inValue.Body.taskIDKey = taskIDKey;
            return ((ToDoApp.BikeWebService.BikeWebServiceSoap)(this)).GetTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ToDoApp.BikeWebService.GetTasksResponse> ToDoApp.BikeWebService.BikeWebServiceSoap.GetTasksAsync(ToDoApp.BikeWebService.GetTasksRequest request) {
            return base.Channel.GetTasksAsync(request);
        }
        
        public System.Threading.Tasks.Task<ToDoApp.BikeWebService.GetTasksResponse> GetTasksAsync(ToDoApp.BikeWebService.User user) {
            ToDoApp.BikeWebService.GetTasksRequest inValue = new ToDoApp.BikeWebService.GetTasksRequest();
            inValue.Body = new ToDoApp.BikeWebService.GetTasksRequestBody();
            inValue.Body.user = user;
            return ((ToDoApp.BikeWebService.BikeWebServiceSoap)(this)).GetTasksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ToDoApp.BikeWebService.AddOrderResponse> ToDoApp.BikeWebService.BikeWebServiceSoap.AddOrderAsync(ToDoApp.BikeWebService.AddOrderRequest request) {
            return base.Channel.AddOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ToDoApp.BikeWebService.AddOrderResponse> AddOrderAsync(ToDoApp.BikeWebService.User user, ToDoApp.BikeWebService.Order order) {
            ToDoApp.BikeWebService.AddOrderRequest inValue = new ToDoApp.BikeWebService.AddOrderRequest();
            inValue.Body = new ToDoApp.BikeWebService.AddOrderRequestBody();
            inValue.Body.user = user;
            inValue.Body.order = order;
            return ((ToDoApp.BikeWebService.BikeWebServiceSoap)(this)).AddOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ToDoApp.BikeWebService.EditOrderResponse> ToDoApp.BikeWebService.BikeWebServiceSoap.EditOrderAsync(ToDoApp.BikeWebService.EditOrderRequest request) {
            return base.Channel.EditOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ToDoApp.BikeWebService.EditOrderResponse> EditOrderAsync(ToDoApp.BikeWebService.User user, ToDoApp.BikeWebService.Order order, ToDoApp.BikeWebService.Order orderOld) {
            ToDoApp.BikeWebService.EditOrderRequest inValue = new ToDoApp.BikeWebService.EditOrderRequest();
            inValue.Body = new ToDoApp.BikeWebService.EditOrderRequestBody();
            inValue.Body.user = user;
            inValue.Body.order = order;
            inValue.Body.orderOld = orderOld;
            return ((ToDoApp.BikeWebService.BikeWebServiceSoap)(this)).EditOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ToDoApp.BikeWebService.DeleteOrderResponse> ToDoApp.BikeWebService.BikeWebServiceSoap.DeleteOrderAsync(ToDoApp.BikeWebService.DeleteOrderRequest request) {
            return base.Channel.DeleteOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ToDoApp.BikeWebService.DeleteOrderResponse> DeleteOrderAsync(ToDoApp.BikeWebService.User user, int orderId) {
            ToDoApp.BikeWebService.DeleteOrderRequest inValue = new ToDoApp.BikeWebService.DeleteOrderRequest();
            inValue.Body = new ToDoApp.BikeWebService.DeleteOrderRequestBody();
            inValue.Body.user = user;
            inValue.Body.orderId = orderId;
            return ((ToDoApp.BikeWebService.BikeWebServiceSoap)(this)).DeleteOrderAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BikeWebServiceSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BikeWebServiceSoap)) {
                return new System.ServiceModel.EndpointAddress("http://178.235.60.107:7500/BikeWebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return BikeWebServiceSoapClient.GetBindingForEndpoint(EndpointConfiguration.BikeWebServiceSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return BikeWebServiceSoapClient.GetEndpointAddress(EndpointConfiguration.BikeWebServiceSoap);
        }
        
        public enum EndpointConfiguration {
            
            BikeWebServiceSoap,
        }
    }
}
